language: csharp
solution: SunriseSunsetCalculator.sln

branches:  
  only:
    - master

before_install:
  - sudo apt-get install nunit-console
  - nuget restore SunriseSunsetCalculator.sln

install:
  - sudo apt-get install -y gtk-sharp2

script:
  - xbuild /p:Configuration=Release SunriseSunsetCalculator.sln

after_script:
  - nunit-console SunriseSunsetCalculatorTest/bin/Release/SunriseSunsetCalculatorTest.dll

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003121
      mono: latest
      env: DOTNETCORE=1
    - mono: latest